### ISSUE TITLE
Going through DownloadActivity breaks downloading if multiple downloads are started at the same time

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#104]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/103) by Karthik T (Bitbucket: [ktaragorn](https://bitbucket.org/ktaragorn), GitHub: [ktaragorn](https://github.com/ktaragorn)).**

----------------------------------------

To replicate, start multiple downloads by calling `DownloadActivity` multiple times. Chances are only the first one will stick. 

If `DownloadActivity` is bypassed and the code is inlined at the call site, it works correctly, by downloading all the games.

**Comment by MikuAuahDark** [comment]
I don't think this is supported scenario of using LOVE `DownloadActivity`. Please comment below if you think otherwise.
