### ISSUE TITLE
Backspace problem

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#111]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/110) by bio1712 (Bitbucket: [bio1712](https://bitbucket.org/bio1712), GitHub: [bio1712](https://github.com/bio1712)).**

----------------------------------------

I use the love.keypressed module to erase chars.

I tested my app on 3 different devices, and it worked well on my Samsung Galaxy S5 and on an I-Inn tablet.

The behavior is correct, I can erase my strings well.

But when i tested it on a Lenovo a7600h it didn't work.
When I press the backspace button for the first time it works well, but when I press the next times it doesn't works.

However, I can fix this bug using love.keyboard.setKeyRepeat(true)

Sorry for my bad english.

**Comment by bio1712** [comment]
I can't reproduce this issue anymore.
It might has already been fixed.

**Comment by MikuAuahDark** [comment]
Could be fixed in SDL. Closed.
