### ISSUE TITLE
Making debug release crashes on Linux when love.window.setMode() sets the wrong width or height

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#126]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/125) by Kasper Eriksen (Bitbucket: [kasperelo](https://bitbucket.org/kasperelo), GitHub: [kasperelo](https://github.com/kasperelo)).**

----------------------------------------

If you write
love.window.setMode(width, height)
replacing width and height with numbers not identical to the devices width and height, you get an java.lang.ArrayIndexOutOfBoundsException when trying to run 'ant debug' on Linux Mint 17.2. However, 'ant release' still seems to work. This is obviously a minor problem, I just wanted to make you aware of its existence.

**Comment by MikuAuahDark** [comment]
Ant build system is no longer supported. Try using Gradle.
