### ISSUE TITLE
Add precompiled portrait and landscape apk's

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#141]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/140) by Gustavo Alberto Lara Gómez (Bitbucket: [Gustavo Lara](https://bitbucket.org/Gustavo Lara), ).**

----------------------------------------

I think it would be practical to have 2 apk's ready to go on the downloads section, something like:
* love-android-0.10.2-release-portrait.apk
* love-android-0.10.2-release-landscape.apk

**Comment by MikuAuahDark** [comment]
Duplicate of #175.
