### ISSUE TITLE
Android Audio 0.5 second delay fix

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#144]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/143) by Miku AuahDark (Bitbucket: [AuahDark](https://bitbucket.org/AuahDark), ).**

----------------------------------------

Changing `device->NumUpdates` to 1 in ALc.c (line 3110) seems fix the 0.5 second audio delay in Android. Tested in Android 4.2.2 and audio delay is gone.

```
#!diff

diff --git a/jni/openal-soft-1.17.0/Alc/ALc.c b/jni/openal-soft-1.17.0/Alc/ALc.c
index f7f7b63..1502056 100644
--- a/jni/openal-soft-1.17.0/Alc/ALc.c
+++ b/jni/openal-soft-1.17.0/Alc/ALc.c
@@ -3107,7 +3107,12 @@ ALC_API ALCdevice* ALC_APIENTRY alcOpenDevice(const ALCchar *deviceName)
     device->FmtChans = DevFmtChannelsDefault;
     device->FmtType = DevFmtTypeDefault;
     device->Frequency = DEFAULT_OUTPUT_RATE;
+#ifdef __ANDROID__
+	//Android fix audio delayed
+	device->NumUpdates = 1;
+#else
     device->NumUpdates = 4;
+#endif
     device->UpdateSize = 1024;
 
     if(!PlaybackBackend.getFactory)

```

**Comment by MikuAuahDark** [comment]
Patches no longer valid as love-android now uses OpenAL-soft 1.19.1.
