### ISSUE TITLE
please remove mimeType for intent-filter

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#145]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/144) by Anonymous.**

----------------------------------------

on my device, the .love file return null mime type, so I cannot open the .love file directly.
I have to remove the mimeType line and build a new apk to make it works.
please kindly remove mimeType for future build.

<intent-filter>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <data android:scheme="file" />
  <data android:pathPattern=".*\\.love" />
  <data android:host="*" />
</intent-filter>

**Comment by MikuAuahDark** [comment]
This needs more investigation. Recent Android (since Nougat) also prohibits `file://` URI so this is confusion on its own.

**Comment by MikuAuahDark** [comment]
Please see https://love2d.org/forums/viewtopic.php?f=3&t=88668
