### ISSUE TITLE
Add NFC

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#149]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/148) by Germán Cruz (Bitbucket: [gercruz](https://bitbucket.org/gercruz), GitHub: [gercruz](https://github.com/gercruz)).**

----------------------------------------

I'm interested in adding NFC functionality to Löve Android
If some guidance is provided I can collaborate on this task.

Is this viable?

R,

**Comment by MikuAuahDark** [comment]
What is your use-case? I don't think game framework needs NFC functionality.

**Comment by MikuAuahDark** [comment]
Closed as there's no further activity. If you have any use case, let me know.
