### ISSUE TITLE
Add support to Gamma Correction

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#151]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/150) by Gustavo Guimaraes (Bitbucket: [Ghust1995](https://bitbucket.org/Ghust1995), ).**

----------------------------------------

Gamma correction does not work even on phones that was supposed to support it.

**Comment by MikuAuahDark** [comment]
Blocked by love2d/love#1106

**Comment by slime73** [comment]
Do we know if `t.gammacorrect` works as expected on Android devices which [have](https://opengles.gpuinfo.org/listreports.php?eglextension=EGL_KHR_gl_colorspace) the `EGL_KHR_gl_colorspace` extension?

I still want to do the virtual backbuffer thing on devices that don't support that extension since it's not super widely available, but it'd be good to know if things already work when it's available.

**Comment by MikuAuahDark** [comment]
Gamma correct rendering in Android is supported as of love2d/love@65667c0f18558f0387c57b0125ec9abcbd5ad980 (which needs `EGL_KHR_gl_colorspace`).
