### ISSUE TITLE
project.properties sets ant target to android-25, causing ant debug to fail

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#156]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/155) by 25A0 (Bitbucket: [25A0](https://bitbucket.org/25A0), GitHub: [25A0](https://github.com/25A0)).**

----------------------------------------

I followed the 'Building LOVE for Android' guide, but `ant debug` kept failing with the following error message:

```
BUILD FAILED
[...]/tools/ant/build.xml:538: Unable to resolve project target 'android-25'
```

I was only able to fix this by replacing `target=android-25` with `target=android-19` in `project.properties`.

If the guide instructs you to set up a complete toolchain for android 19, shouldn't `project.properties` then set the ant target to android 19, too? It seems odd to me that I have to change a file that ships with the repo in order to make the build work.

**Comment by MikuAuahDark** [comment]
Ant build system is no longer supported. Use Gradle.
