### ISSUE TITLE
Publish the compiled native library to a gradle repository

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#162]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/161) by Anonymous.**

----------------------------------------

Publishing the library artifacts to a gradle repository would allow people to create love2d android apps with minimal work . It would hopefully also lower your burden since fewer less-experienced game developers would ask for your help here.

http://florentchampigny.com/publish-a-library-to-jcenter

(this came up after discussion at f-droid https://gitlab.com/fdroid/rfp/issues/285#note_50557030 )

**Comment by awalgarg** [comment]
Hey @IzzySoft, do you have any idea what the path is to add the love2d app to f-droid? And in the meantime, would you be willing to publish it on your repo from the apk releases on https://github.com/love2d/love/releases/? Thanks!

**Comment by IzzySoft** [comment]
My repo doesn't accept games. And a good start would be opening a [Request for Packaging](https://gitlab.com/fdroid/rfp/issues).

**Comment by awalgarg** [comment]
@IzzySoft Cool, thanks. (FWIW, and I realize this is grasping at straws for little benefit, love2d is a generic-ish 2d engine which can be used for more than just games, but it is certainly not a game in itself).

---

@MikuAuahDark I hope it's okay with you/love2d team for the app to be published on f-droid? It looks like explicit consent from the authors is a soft-requirement for publishing on f-droid. Thank you!

**Comment by MikuAuahDark** [comment]
Actually I had intention to distribute to F-droid but on its current state
it's just less useful.

If you managed it please pick the ones with microphone support when
possible.

Pada tanggal Kam, 18 Nov 2021 05.05, Awal Garg ***@***.***>
menulis:

**Comment by awalgarg** [comment]
Thanks you @MikuAuahDark, I've filed this RFP ticket on the f-droid tracker https://gitlab.com/fdroid/rfp/-/issues/1920.

**Comment by IzzySoft** [comment]
> If you managed it please pick the ones with microphone support when possible.

If those have a specific build flavor, just mention that in the RFP so it can/will be used by the build recipe later.

**Comment by MikuAuahDark** [comment]
The one with microphone support is the "normal" flavor, thanks.

**Comment by awalgarg** [comment]
@MikuAuahDark The fdroid bot has generated a report with some issues https://gitlab.com/fdroid/rfp/-/issues/1920#note_737306189. Looks like the main issues are fastlane setup and the precompiled binaries from sdl, luajit and libmpg.

**Comment by MikuAuahDark** [comment]
I think moving this conversation somewhere else is a good idea. #220
