### ISSUE TITLE
Touches are sometimes lost with 3 or more fingers on screen

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#166]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/165) by Josip Miskovic (Bitbucket: [jmiskovic](https://bitbucket.org/jmiskovic), GitHub: [jmiskovic](https://github.com/jmiskovic)).**

----------------------------------------

Steps to reproduce:

0) Build APK and load game.love containing following code in main.lua

```
#!lua
function love.draw()
  love.graphics.print(#love.touch.getTouches(), 100, 100)
end
```

Enable 'Show touches' and 'Pointer location' in Android Developer options. Execute Love2D with game.love.

2) Touch the screen with three fingers as close as possible. Both device and Love2D will interpret this as single touch.

3) Spread out fingers until device reports 3 touches.

4) See that the number of touches reported by Love2D is 0, which is different from what device reports.

![love_touch_issue.png](https://bitbucket.org/repo/A8Abzz/images/1653015472-love_touch_issue.png)

Note that this will occasionally occur in normal use.  It happens more often when all three touches are pressed simultaneously across the screen, and the easiest way to reproduce is described above.

I have touchscreen on laptop running linux, and I could not reproduce this issue there.

**Comment by MikuAuahDark** [comment]
Sounds like device/ROM-specific issue. Closing.
