### ISSUE TITLE
Immersive mode lost after hiding soft keyboard

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#167]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/166) by FreeG (Bitbucket: [FreeG](https://bitbucket.org/FreeG), GitHub: [FreeG](https://github.com/FreeG)).**

----------------------------------------

Hello, in my app the navigation menu will remain visible after I use

```
#!lua

love.keyboard.setTextInput(false)
```

to dismiss the soft keyboard.
I suppose the SDL_Window flags are somewhat lost.

To fix the problem I created a patch which populates the ```HideScreenKeyboard``` device callback, where I put the code to turn on again immersive mode (as this is always the case on Android, as far as I understood). I am not sure this is the best possible fix, but at least should give you an idea of what I'm talking about.

**Comment by MikuAuahDark** [comment]
I don't have phone with soft navigation buttons. Can someone test if this is still the case?

**Comment by MikuAuahDark** [comment]
I think 31d7aff fixes this issue.
