### ISSUE TITLE
Screen Orientation - Portrait and Landscape

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#175]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/174) by Ashley Ennerst (Bitbucket: [Ashley James Ennerst](https://bitbucket.org/Ashley James Ennerst), ).**

----------------------------------------

Please make a function to switch between portrait and landscape and have a parameter for it in the love.conf. Thank you

**Comment by MikuAuahDark** [comment]
`love.window.setMode` and `love.window.updateMode` can be used to change screen orientation by specifying landscape/portait aspect ratio resolution.

**Comment by cristoferfb** [comment]
Sorry can u give a more clear (if it possible a functional example) about how to change the screen orientation in android devices?

Default my game is in Landscape mode and I do this (basically invert the aspect ratio): 
```
function love.load()
    love.window.updateMode(love.graphics.getHeight(), love.graphics.getWidth())
end
```

I too have change the orientation in the AndroidManifest:

` android:screenOrientation="sensorPortrait"`

But any of this changes did not works for me. I think something like change the screen orientation should be a trivial task.

**Comment by cristoferfb** [comment]
Well I think Love should have a more intuitive way for get it work. The [FAQ](https://github.com/love2d/love-android/wiki/FAQ---Frequently-Asked-Questions#how-to-change-screen-orientation-to-portrait)  show me 3 ways for change the screen orientation but `love.window.setMode` and `love.window.updateMode` way have inconsistence behaviour, they take an arbitrary time for complete the screen orientation change so they aren't safe ways for the task:

_note: the first [msg] is from the end of `love.load()` all the next [msg] are from the beginning of `love.draw()`_

![image](https://user-images.githubusercontent.com/28372608/81027408-a8912f80-8e4b-11ea-9c32-609ee3ccf2fb.png)

the `love.conf` way I not sure if it is free of this problem but at least it take dramatically less time for complete the change:

![image](https://user-images.githubusercontent.com/28372608/81027714-c14e1500-8e4c-11ea-81c6-eb9135580eeb.png)

According to the documentation: 

> If a file called conf.lua is present in your game folder (or .love file), it is run before the LÖVE modules are loaded

but the change occurr only in the first call to ` love.draw ()` , at least in the `love.load()` the change not occurr and the documentation not is clear what is the position of `love.load()` about to other hooks like `love.conf()` , documentation say the next about  `love.load()`:

> This function is called exactly once at the beginning of the game.

but I suppose `love.conf()` is called before any other callback and the change in the screen orientation should be available in the call of `love.load()`.

I believe a function that's wait for the screen orientation change can be a more robust way to do the task.
