### ISSUE TITLE
Gradle assemble error.

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#180]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/179) by Miku AuahDark (Bitbucket: [AuahDark](https://bitbucket.org/AuahDark), ).**

----------------------------------------

A change is missing to make compiling with API 26 work correctly. The root `build.gradle` must be changed to this one

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

allprojects {
    repositories {
        google()
        jcenter()
    }
}

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

repositories {
    google()
}
```

I hope that `build.gradle` is used.

Related links about this issue:

* https://bitbucket.org/AuahDark/love-android-sdl2/issues/1/building-doesnt-work

* https://bitbucket.org/AuahDark/love-android-sdl2/commits/deb58d21df1e8c50d8b7b4efb72fe85e3182efc0

**Comment by MikuAuahDark** [comment]
No longer relevant. LOVE for Android now requires API 28 to compile.
