### ISSUE TITLE
Black screen on open apk

### ISSUE THREAD

**Issue by cristoferfb** [love2d/love-android#190]
Hi, I get a black screen when open my apk. There is [my logcat](https://pastebin.com/5E7BVWV0)
When I press home screen button, I can focus back to the game and it render properly. In some ocations it render properly in the first startup. I use the last love-11.3-android-embed.apk for package my game.

Adjunt signed apk and source code: [codeontouch.zip](https://github.com/love2d/love-android/files/4572258/codeontouch.zip)

I notice some error codes in line 417 of the logcat

```
05-03 20:32:44.693  1281  2647 I ActivityManager: Killing 9569:com.cristoferfb.cot/u0a187 (adj 900): remove task
05-03 20:32:44.696  1281  1298 W libprocessgroup: kill(-9569, 9) failed: No such process
05-03 20:32:44.722 27657  5247 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
05-03 20:32:44.730 27657  5247 I GmsCoreXrpcWrapper: Returning a channel provider with trafficStatsTag=12803
05-03 20:32:44.734  1281  1298 W libprocessgroup: kill(-9569, 9) failed: No such process
05-03 20:32:44.746  1281  2047 W InputDispatcher: channel '7b8c6a3 com.cristoferfb.cot/org.love2d.android.GameActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
```

**Comment by MikuAuahDark** [comment]
If you try the master branch, does the problem still exist?

**Comment by cristoferfb** [comment]
@MikuAuahDark I use the last release I am not sure if I can use the master branch because I not compile the project, I use the pre-compiled apk and inject my source code.

**Comment by MikuAuahDark** [comment]
Can you try this [APK](https://github.com/love2d/love-android/files/4572419/app-embed-release-unsigned.apk.zip)? It's actually APK but with ZIP extension appended.

**Comment by cristoferfb** [comment]
Thanks for take the time for compiled it, I tried with it but I have the same problem, in the most ocations I get a black screen. In this time I notice an error from my source code in my `love.mousepressed` event this error is not importat because is a logic error from my source code but it tell me the problem is only in the render task of love because all other logics works.

**Comment by MikuAuahDark** [comment]
Thanks. I just checked there's new version of SDL, I'll try if using the latest version fixes the issue.

**Comment by cristoferfb** [comment]
I notice other strange behaviour, I don't know if it will be related but when I switch the screen orientation in the android manifest:

`<activity android:configChanges="orientation|screenSize" android:label="Code on Touch" android:launchMode="singleTask" android:name="org.love2d.android.GameActivity" android:screenOrientation="portrait">`

It change the `love.graphics.getWidth()` and `love.graphics.getHeight()` properly but all is still drawed in landscape mode.

**Comment by MikuAuahDark** [comment]
Use this method to change screen orientation in LOVE https://github.com/love2d/love-android/wiki/FAQ---Frequently-Asked-Questions#how-to-change-screen-orientation-to-portrait

**Comment by cristoferfb** [comment]
With that methods I get to draw in portrait mode but the love.graphics.getWidth() and love.graphics.getHeight() still have the landscape values ¿That is normal?

**Comment by MikuAuahDark** [comment]
Yeah, changing the orientation from the manifest is UB, use `love.window.setMode`/`love.window.updateMode` as described in the link I provided.

**Comment by cristoferfb** [comment]
Well playing more with the screen orientation I notice the black screen only occurr when I call `love.window.updateMode`, changing the screen orientation from `love.conf` works but the change not is available in the `love.load()` callback as I mentioned in #175

**Comment by cristoferfb** [comment]
Well playing more with the screen orientation I notice the black screen only occur when I call love.window.updateMode() if:

- a portrait width and height are specified in love.conf()

or

- set the android manifest to portrait

I think love is trying to change the screen orientation two times in a bad way.

**Comment by MikuAuahDark** [comment]
I updated `master` branch to SDL 2.0.12. If you can download the latest build artifacts and test the embed APK, I'd appreciate it.

https://github.com/love2d/love-android/actions/runs/95797109
