### ISSUE TITLE
Incorrect graphic dimensions after soft keyboard display.

### ISSUE THREAD

**Issue by ImagicTheCat** [love2d/love-android#191]
Without the fullscreen option, the game is displayed correctly with the status bar until the soft keyboard is displayed: a resize event is triggered and change the dimensions as if the status bar was hidden, effectively cropping the top of the app canvas.

- LÖVE 11.3 APK
- device: Xiaomi Redmi Go

**Comment by MikuAuahDark** [comment]
Can you let me know if this also happends in latest [Actions](https://github.com/love2d/love-android/actions/runs/95797109) artifact? You have to use and sign the normal or playstore variant, not embed.

**Comment by ImagicTheCat** [comment]
Yes, still an issue.
