### ISSUE TITLE
love.filesystem.getSaveDirectory() differs from java-side Context.getFilesDir()

### ISSUE THREAD

**Issue by MrcSnm** [love2d/love-android#193]
So, I'm calling Context.getFilesDir and it is returning:  '/data/user/0/org.love2d.android/files/save/'
While love.filesystem.getSaveDirectory is returning: '/data/data/org.love2d.android/files/save/'
The problem is that I'm wanting to read save files from my game from the java side, and that discrepancy is bugging me.

And that is a really bad problem, because I can't know if in someone's else phone it will be different

**Comment by MikuAuahDark** [comment]
If I remember correctly, `/data/data` is symbolic link to `/data/user/0`. I don't have rooted phone to really check if that's the case though.

**Comment by MrcSnm** [comment]
Okay, so it really is, could make it work, but there is another question: can I get the .love Identity from java side?

**Comment by MikuAuahDark** [comment]
No. You have to wrap it as JNI call.

**Comment by MrcSnm** [comment]
How would I do that?

**Comment by MikuAuahDark** [comment]
Somewhere in your own C++ code, access the `love.filesystem` module using C++
```cpp
// JNI
#include <jni.h>

// love.filesystem
#include "modules/filesystem/Filesystem.h"

extern "C" JNIEXPORT jstring JNICALL Java_org_love2d_android_GameActivity_getIdentity(JNIEnv *env, jobject obj)
{
	auto instance = love::Module::getInstance<love::filesystem::Filesystem>(love::Module::M_FILESYSTEM);
	return env->NewStringUTF(instance->getIdentity());
}
```
And in GameActivity.java, add
```java
public native string getIdentity();
```

**Comment by MrcSnm** [comment]
> Somewhere in your own C++ code, access the `love.filesystem` module using C++
> 
> ```c++
> // JNI
> #include <jni.h>
> 
> // love.filesystem
> #include "modules/filesystem/Filesystem.h"
> 
> extern "C" JNIEXPORT jstring JNICALL Java_org_love2d_android_GameActivity_getIdentity(JNIEnv *env, jobject obj)
> {
> 	auto instance = love::Module::getInstance<love::filesystem::Filesystem>(love::Module::M_FILESYSTEM);
> 	return env->NewStringUTF(instance->getIdentity());
> }
> ```
> 
> And in GameActivity.java, add
> 
> ```java
> public native string getIdentity();
> ```

Thanks, that really is amazing
Do I need to include the package name in the function name?
Would I need to create a .so file and then in the GameActivity call System.loadLibrary('filename')?

**Comment by MikuAuahDark** [comment]
You can just add that to LOVE `android.cpp` and LOVE `GameActivity.java` if you really don't want to bother with additional .so file.
