### ISSUE TITLE
Add a note about running on Ouya

### ISSUE THREAD

**Issue by xordspar0** [love2d/love-android#198]
I'm able to get my games working on an Ouya, but I needed to make one minor change to the AndroidManifest.xml:

```diff
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 0d823b7b..ea9d6fa3 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -3,7 +3,6 @@
   android:installLocation="auto" xmlns:android="http://schemas.android.com/apk/res/android">
   <uses-permission android:name="android.permission.INTERNET" />
   <uses-permission android:name="android.permission.VIBRATE" />
-  <uses-permission android:name="android.permission.BLUETOOTH" />
   <uses-permission android:name="android.permission.RECORD_AUDIO" />
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:maxSdkVersion="23" />
   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" />
```

BluetoothManager is supported in Android API 18+, but the Ouya only has API version 16. I disabled it by removing that line.

Could this be documented somewhere? I have a couple notes:

1. Has the Github wiki officially replaced the Bitbucket one, or is a migration still in progress? The LOVE wiki still links to the Bitbucket one, for example here: https://love2d.org/wiki/Game_Distribution#Android
2. The old Bitbucket wiki has a page on how to use the Ouya, but none of the workarounds mentioned there were required for me. Therefore, it's fine if that page isn't copied over, but maybe my workaround could go on a new page for the Ouya.

**Comment by MikuAuahDark** [comment]
> BluetoothManager is supported in Android API 18+, but the Ouya only has API version 16.

Looks like BluetoothManager is used by SDL, but if it fails to run with that Bluetooth permission in place, then it's probably better to fill bugs in SDL.

> Has the Github wiki officially replaced the Bitbucket one, or is a migration still in progress? The LOVE wiki still links to the Bitbucket one, for example here: https://love2d.org/wiki/Game_Distribution#Android

The migration is "quite" complete now. I've changed the links there to point to the new wiki.

**Comment by xordspar0** [comment]
> Looks like BluetoothManager is used by SDL, but if it fails to run with that Bluetooth permission in place, then it's probably better to fill bugs in SDL.

Good point. If Bluetooth can be enabled without trying to use BluetoothManager that would be best.

> I've changed the links there to point to the new wiki.

Thanks!

**Comment by MikuAuahDark** [comment]
I think SDL should perform API level detection already. Please test whetever it's not the case (ie. you encounter crash instead) and report to SDL accordingly.

**Comment by xordspar0** [comment]
Just to follow up on this, I submitted a patch to SDL to fix this and it was accepted: https://bugzilla.libsdl.org/show_bug.cgi?id=5450

**Comment by MikuAuahDark** [comment]
SDL patch applied, thanks.
