### ISSUE TITLE
how to change the icon

### ISSUE THREAD

**Issue by shoucandanghehe** [love2d/love-android#210]
I read the wiki, but I can't find the drawable-* folder in the project

**Comment by castelo3442** [comment]
This video helped me a lot:  https://www.youtube.com/watch?v=SDKwNh0TioE
Long story short: In android Studio, open your project, right-click in love-android/app/scr/main/res, new, image asset, and use your 512x512px .png . The "drawable" folder is inside this "res", but depending how you will make your changes, you won`t need it. Example:
In AndroidManifest:
Replace android:icon="@drawable/love" by the address where your icon was placed. Example: 
              android:icon="@mipmap/ic_launcher" (in mipmap you should see by now lots of formats from original image)

**Comment by shoucandanghehe** [comment]
Ah, I think I found those files
I used the wrong find command before
