### ISSUE TITLE
The screen rotation direction cannot be locked

### ISSUE THREAD

**Issue by shoucandanghehe** [love2d/love-android#211]
Set in AndroidManifest.xml to
`android:screenOrientation="sensorLandscape"`
But the screen can be rotated arbitrarily in the game, including vertical

**Comment by MikuAuahDark** [comment]
Set t.window.resizable=false in love.conf.

Pada tanggal Sab, 14 Agu 2021 23.08, scdhh ***@***.***>
menulis:
