### ISSUE TITLE
Generating an upload key for Android App Bundle output

### ISSUE THREAD

**Issue by JasonNumberThirteen** [love2d/love-android#212]
Hello, I have one question. Is there any way to sign "_Love2D_" game as an "_aab_" file ("_Android App Bundle_")? I was trying to find any clues but I couldn't figure out how to do it. Do you know how to generate an upload key to insert my "_aab_" file to Google Play Console?

**Comment by MikuAuahDark** [comment]
Just use `jarsigner` that's bundled with JDK.

**Comment by JasonNumberThirteen** [comment]
Thank you.
