### ISSUE TITLE
love.mouse returns float on Android but integer on Windows

### ISSUE THREAD

**Issue by FormularSumo** [love2d/love-android#213]
On Windows (and presumably macOS/Linux) love.touch events return a float while love.mouse events return an integer. 
On Android both return floats. Using the touchscreen calls love.touch and love.mouse. Left clicking with a mouse calls also calls both. Right or middle clicking a mouse only calls love.mouse, however it still returns a float. 

```
test = 0
test2 = 0
test3 = 0
test4 = 0
test5 = 0
test6 = 0

function love.mousemoved(x,y)
    test = x .. ' ' .. y
end

function love.mousepressed(x,y)
    test2 = x .. ' ' .. y
end

function love.mousereleased(x,y)
    test3 = x .. ' ' .. y
end

function love.touchmoved(id,x,y)
    test4 = x .. ' ' .. y
end

function love.touchpressed(id,x,y)
    test5 = x .. ' ' .. y
end

function love.touchreleased(id,x,y)
    test6 = x .. ' ' .. y
end

function love.draw()
    love.graphics.print('love.mouse.getPosition:' .. love.mouse.getX() .. ' ' .. love.mouse.getY())
    love.graphics.print('love.mousemoved:' .. test,0,20)
    love.graphics.print('love.mousepressed:' .. test2,0,60)
    love.graphics.print('love.mousereleased:' .. test3,0,80)
    love.graphics.print('love.touchmoved:' .. test4,0,120)
    love.graphics.print('love.touchpressed:' .. test5,0,140)
    love.graphics.print('love.touchreleased:' .. test6,0,160)
end
```
Windows:
![Windows](https://user-images.githubusercontent.com/36278229/131649069-ad749cbb-4d54-4419-8f9b-1a7dedd02aaf.png)
Android:
![Android](https://user-images.githubusercontent.com/36278229/131649270-51510778-6591-4e82-b882-217747ae6470.jpg)

I noticed this because in love.mousemoved I'm checking if mouse has been moved to where I set it with love.mouse.setPoisition, and it wasn't working properly on Android. As a workaround I've done this:
![image](https://user-images.githubusercontent.com/36278229/131657856-fad9eec0-ed09-40a4-87aa-7fc958d32017.png)
but it would make sense if beheaviour was consistent between the operating systems I think?

**Comment by slime73** [comment]
I don't think this is a bug – it can return floats everywhere, it just happens to land on exact integers on some platforms (and that might change in the future). You can do something like `math.abs(prev - current) < 0.01` to see if a number is close to identical to another number.

**Comment by FormularSumo** [comment]
So on Windows mouse positions are always reported as integers while on Android it's more precise? Not sure if it's related but you can see touch events on Windows are for me always returned as floats very very close to integers, either .99999 or .00000 etc while on Android it seems possible to land anywhere in that range.

Also I see how your solution would work but I'll probably stick to what I'm using as it works fine, but thanks!
