### ISSUE TITLE
Help Error: A problem occurred configuring project ':love'.

### ISSUE THREAD

**Issue by Bissiatti** [love2d/love-android#214]
```bash
"SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in

 your project's local properties file at '/love-android-master/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 

get full insights.

* Get more help at https://help.gradle.org"
```

How do I fix this? I'm with the same problem on linux and windows.

**Comment by MikuAuahDark** [comment]
Your Android SDK is not configured properly.

**Comment by Bissiatti** [comment]
> Your Android SDK is not configured properly.

How do I make this?

**Comment by MikuAuahDark** [comment]
https://developer.android.com/studio

Also from the readme:
> Before you start, install **JDK 11** or later. If you intend to build from Android Studio, skip this step as Android Studio **bundles its own** JDK 11.
Install Android SDK with **SDK API 30** and Android **NDK 21.3.6528147**
