### ISSUE TITLE
Debug symbols and deobfuscation file warnings during deployment for Google Play Console

### ISSUE THREAD

**Issue by JasonNumberThirteen** [love2d/love-android#215]
Hello,
I would like to release a game using this tool on Google Play Console. However, when I successfully upload an AAB file and when I go further to check uploaded version, I have two warnings which I cannot get rid of them.

<img width="704" alt="warnings" src="https://user-images.githubusercontent.com/40078536/136552479-65a6d228-b50a-4968-8154-7a064731e660.png">

The first one tells me about "**deobfuscation file**". I'm using minified code, but I checked "traditional" code and this warning was still existing. Do I need to modify something in Gradle files? I used "**gradlew bundleEmbedRelease**" command.

The second warning describes lack of something called "**debugSymbolLevel**". Using [this](https://stackoverflow.com/questions/63373245/how-to-add-debug-symbols-to-build-gradle) method, I tried to implement this by myself, but when I uploaded the new version, this warning didn't disappear. Maybe I did this wrong.

I leave you links which describe both warnings after clicking "**Learn More**" near each of them.

[Obfuscate your code](https://developer.android.com/studio/build/shrink-code#decode-stack-trace)
[Native crash support](https://developer.android.com/studio/build/shrink-code#native-crash-support)

Finally, simple question. **Do you know any tips** (or even solutions) **to eliminate both of these warnings?**

**Comment by JasonNumberThirteen** [comment]
OK, I'll check that. Thank you very much!

**Comment by MikuAuahDark** [comment]
Yes in `love/build.gradle` because that's the module that uses NDK.

**Comment by MikuAuahDark** [comment]
Because we're still using legacy `ndk-build`, not CMake.

**Comment by JasonNumberThirteen** [comment]
I added this and it didn't disappear.

**Comment by JasonNumberThirteen** [comment]
Unfortunately, nothing shows up... Added "**android.defaultConfig.ndk.debugSymbolLevel = 'FULL'**" as you have suggested, built again and there's no "**native-debug-symbols.zip**" archive. I've even tried with "SYMBOL_TABLE" and the archive hasn't been created.

**Comment by JasonNumberThirteen** [comment]
Hi, any new progress in these symbols?

**Comment by JasonNumberThirteen** [comment]
Which folder do I have to get "**.so**" files from? "**arm64-v8a**", "**armeabi-v7a**" or both?
