### ISSUE TITLE
Consider these changes

### ISSUE THREAD

**Issue by Vixeliz** [love2d/love-android#216]
Hello! I was wondering if you could make these changes or if I can do a pull request. The changes are present in this issue (https://github.com/Lzhiyong/termux-ndk/issues/64#issuecomment-941799781). It allows for building this on android termux for being able to develop on device. Again can make a pull request if it would be easier.

**Comment by MikuAuahDark** [comment]
I think that change also solves compilation errors in Linux when using clang. I may consider it.

**Comment by MikuAuahDark** [comment]
Done. love2d/love@7310fde7b90ce4d7cb5ae05fd54efaa8af27a6a8
