### ISSUE TITLE
Using enet causes `Cannot push enet peer to Lua: pointer value %p is too large`

### ISSUE THREAD

**Issue by kungfoo** [love2d/love-android#222]
I tried updating my app to the newest `main` branch state and it is using `enet` for communication with the server.

When I try to connect the `enet` host, the app throws this exception. This is with a debug build on a Pixel 4 (updated to Android 12).

Not sure if I'm building it wrong, or if there _is_ something wrong.

**Comment by MikuAuahDark** [comment]
Looks like the fix is trivial. love2d/love@4f491c2e6162ff880818b4725a0c59912ca2c6c7 just needs to be applied to ENet too.

**Comment by kungfoo** [comment]
Just fyi: something similar happens when `nogame.lua` is loaded:

    [LOVE] Error: [string "nogame.lua"]:31: Cannot push love object to Lua: pointer value 0xb400007a6a05d080 is too large

**Comment by slime73** [comment]
Just to confirm, your local code has the change AuahDark linked?

**Comment by kungfoo** [comment]
Disregard that comment above. I switched branches and forgot to update the submodule. `nogame.lua` works fine, using `enet` is what crashes it.

**Comment by kungfoo** [comment]
I ported a really ugly hacky version of the fix and can report that it works. I can try preparing a PR for upstream, if needed.

**Comment by MikuAuahDark** [comment]
Sure. I was bit puzzled since I don't know the obvious location where actually those keys are used.

**Comment by slime73** [comment]
I think it's just `compute_peer_key` / `push_peer` (in enet.cpp) that need to change, similar to the main LÖVE commit. I'll see about implementing it shortly.

**Comment by kungfoo** [comment]
That's what i did. I just ported the methods to the types `EnetPeer`. I'm
pretty sure there is a nicer way to do it, though.
