### ISSUE TITLE
update wiki

### ISSUE THREAD

**Issue by shoucandanghehe** [love2d/love-android#223]
I noticed that the wiki contains a lot of outdated information which should be kept up to date
For example in `Game Packaging`
```
How to package the apk with your own LÖVE game
Create a folder named assets in app/src/main of the root of the love-android repository and place your game in it; you can use the shell (Windows user should use copy instead of cp):
```
Apparently it should now be `app/src/embed/assets` instead of `app/src/main/assets`
Also in the same chapter
`How to change the icon`
`mdpi` should be `48*48` not `42*42`
`xxxhdpi` should be `192*192`, but the wiki doesn't say

**Comment by shoucandanghehe** [comment]
Meanwhile I think the README should direct the user to a detailed tutorial in the wiki
like [this](https://github.com/love2d/love-android/blob/b367b3733d32e1ea734d8f1215d94cb6c88fc0c4/README.md?plain=1#L60)

**Comment by MikuAuahDark** [comment]
Either `app/src/main/assets` or `app/src/embed/assets` works due to how Gradle works.

In general, the repository wiki is (bit) outdated except the FAQ page. I updated the Game Packaging wiki for you.
