### ISSUE TITLE
love apk 11.4 does not register the .love extension automatically when installed

### ISSUE THREAD

**Issue by Sylfir** [love2d/love-android#229]
Hi, i installed today the newest apk version 11.4. When i try to run the .love file, there is no choice from the android OS to run the installed love apk. I quess it is something around registering the .love extension.

Tried again uninstalling the 11.4 and installing the 11.3 version of apk. The 11.3 apk shows dialog "allow acess to media files?". I allow it. This is missing in 11.4.

Have a nice day. :)

**Comment by Sylfir** [comment]
Maybe i explained it wrong. Ok, is the apk on this git signed? If i look at the installed apk permission settings on android 9 i see everything gray (disabled). There is no way to run it on 11.4.

**Comment by MikuAuahDark** [comment]
Yes the APKs in the releases page are signed.

**Comment by MikuAuahDark** [comment]
Unfortunately there's nothing LOVE can do for `*.love` file association registration.
