### ISSUE TITLE
No game when there is one?

### ISSUE THREAD

**Issue by Hellscap3d** [love2d/love-android#232]
So I use android 11, and I wanted to try a game that uses love, so I downloaded love. I used zarchiver to put the .love file contents in /sdcard/Android/data/org.love2d.android/files/games/lovegame
Weird thing is, the lovegame dir didnt exist, I don't know if thats intended or not. So after I extracted the game's .love file in the correct dir, then I started the android app. Said "no game" even though its there. Can anyone help me with this?

**Comment by MikuAuahDark** [comment]
You need to create the directory if it doesn't exist.

**Comment by Hellscap3d** [comment]
> You need to create the directory if it doesn't exist.

I did, it refused to work until I reinstalled love
