### ISSUE TITLE
12.x Error: dlopen failed: library "libluajit.so" not found.

### ISSUE THREAD

**Issue by modcos** [love2d/love-android#247]
When I launch any .love archive I get: Error: dlopen failed: library "libluajit.so" not found.
When I add the "luajit" target to build.gradle, I get:

Execution failed for task ':app:buildCMakeDebug[arm64-v8a][OpenAL,love_android,etc]'.
> Unexpected native build target luajit. Valid values are: love, theora-static, love_3p_luahttps, ex-common, megatest, vorbisfile-static, love_3p_lodepng, love_3p_xxhash, love_3p_enet, love_3p_wuff, harfbuzz, love_3p_glslang, love_3p_lua53, SDL2, love_3p_physfs, zlibstatic, love_3p_spirv_cross, ogg-static, common, modplug-static, love_3p_noise1234, love_3p_luasocket, love_3p_ddsparse, harfbuzz-subset, love_3p_box2d, love_3p_glad, zlib, love_3p_lz4, sdl_headers_copy, vorbis-static, freetype, lua51, SDL2main

**Comment by MikuAuahDark** [comment]
I also filled bug report to Android Studio about this issue. https://issuetracker.google.com/issues/274493986
