### ISSUE TITLE
can't install build release apk 

### ISSUE THREAD

**Issue by boris-741** [love2d/love-android#250]
OS Androoid 11
last github copy (11.5)
debug build instal and run but release won't install on real phone Samsung M01

normal/embed/Record/NoRecord not successful
lib armeabi-v7a included in the package (I checked with zip)

debug build instal and run successful
debug and release build from android studio 2022.2.1 os windows

**Comment by MikuAuahDark** [comment]
Release APK that's compiled from Android Studio is not signed. Android prevents anyone installing unsigned APK. You must sign it first!
