### ISSUE TITLE
Termux Activity Manager's problem

### ISSUE THREAD

**Issue by destime224** [love2d/love-android#255]
- When i'm trying start **Löve** with command `am start -d file://$(realpath game.love) -n org.love2d.android/.GameActivity` game doesn't launch and shows _no game screen_

- `realpath game.love` is `/data/data/com.termux/files/home/game.love`

- `termux-info`
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=28465
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
\# sources.list
deb https://mirror.surf/termux/termux-main/ stable main
\# x11-repo (sources.list.d/x11.list)
deb https://mirror.surf/termux/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.39.1
Android version:
10
Kernel build information:
Linux localhost 4.4.192-perf+ \#1 SMP PREEMPT Fri Sep 3 15:22:30 WIB 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51

**Comment by MikuAuahDark** [comment]
LOVE doesn't have access to `/data/data/com.termux/files/home/game.love` as part of Android file sandboxing. Furthermore, starting in Android 7, passing `file://` URI is banned.

Unfortunately it's not something we can fix.
