### ISSUE TITLE
Running through the LÖVE Loader seems to get a fresh save dir each time

### ISSUE THREAD

**Issue by akkartik** [love2d/love-android#257]
I have an app that saves some settings across restart in the save dir. It doesn't persist such settings when run from the LÖVE loader. But it does so when run from the browser download window. Does this seem expected?

**Comment by akkartik** [comment]
Yeah you're right, the directory doesn't change. Let me dig a little further. I wonder if the directory is getting cleared between invocations.

**Comment by akkartik** [comment]
Yes, I see an error when running from the Loader.

```
function love.load()
  Info = love.filesystem.getInfo('config')
  Status, Err = love.filesystem.write('config', 'abc')
  Info2 = love.filesystem.getInfo('config')
end

function love.draw()
  love.graphics.print(tostring(Info), 10,10)
  love.graphics.print(tostring(Status)..'/'..tostring(Err), 10,40)
  love.graphics.print(tostring(Info2), 10,70)
end
```

This prints:
```
Could not set write directory.
```

**Comment by akkartik** [comment]
Thank you!

I'm having some trouble trying out the artifact:

```
App not installed as package appears to be invalid.
```

I tried multiple browsers, with and without nightly.link.

**Comment by MikuAuahDark** [comment]
APK installs fine in here. Make sure to extract the APK inside the zip artifact.

**Comment by akkartik** [comment]
Yes, I confirmed that. Steps I was following were to unzip and then try to install the .apk inside the zip file.

I've also confirmed that it's not some detail about which app is doing the installation:

_Baseline:_ If I download https://github.com/love2d/love/releases/download/11.5/love-11.5-android.apk from the https://love2d.org/ frontpage to my own server, then download it from my server to my phone using Firefox and install it, everything works fine :heavy_check_mark:

However, if I download [love-android.apk](https://github.com/love2d/love-android/actions/runs/7306340688/artifacts/1132325592) from https://github.com/love2d/love-android/actions/runs/7306340688, then unzip it and publish the .apk inside to my own server, then download it from my server to my phone using Firefox and install it, I get the above error :heavy_multiplication_x:  (This approach doesn't require me to go through the file manager app on my phone.)

**Comment by akkartik** [comment]
I can also reproduce the problem on my tablet.

I'll keep an eye on newer artifacts. If I recall correctly I've seen this problem before, but I _am_ sometimes able to install artifacts.

BTW, I notice the v12 branch artifact has expired. I'm going to keep an eye out for a new artifact on that branch and test it out as well.

**Comment by MikuAuahDark** [comment]
But have you uninstalled previous LOVE app?

**Comment by akkartik** [comment]
Thank you very much for the hotfix release. Yes, I was uninstalling LÖVE each time. But I was able to get it installed now from https://love2d.org

**Comment by MikuAuahDark** [comment]
Oh interesting, because that APK comes from GitHub Actions too. The only difference is it's signed with LOVE Android keystore instead of debug keystore.
