### ISSUE TITLE
Version 11.5 does not work on Android 9

### ISSUE THREAD

**Issue by risejs** [love2d/love-android#260]
ABI: armeabi-v7a
Test: [LabyrinthOfLegendaryLoot-1.12.love](https://dominaxis-games.itch.io/labyrinth-of-legendary-loot)

**Comment by MikuAuahDark** [comment]
Could you give more information about what exactly doesn't work?

**Comment by risejs** [comment]
0. Tap "LÖVE for Android" > Nothing happens (version 11.4 works here)
1. Tap "LÖVE Loader" > Select "Test.love" > Nothing happens
2. Tap "Test.love" > Select "LÖVE for Android" > Nothing happens (version 11.4 works here)

**Comment by MikuAuahDark** [comment]
It works as expected in here (using LÖVE Loader)
![Screenshot_20231210_174511](https://github.com/love2d/love-android/assets/7500438/9cc54303-8946-42dd-a956-934fd5429fc9)

**Comment by risejs** [comment]
It doesn't work on Android 9 armeabi-v7a.

**Comment by MikuAuahDark** [comment]
Could you provide video showing how you atempted to launch the game? If privacy is a concern, feel free to DM me in Discord (please don't send friend request) by joining the LOVE Discord first.

**Comment by risejs** [comment]
adb logcat --buffer=crash
![fatal_exception_main](https://github.com/love2d/love-android/assets/16482311/30226bb7-c52b-4303-91b2-17710cd75b49)

**Comment by MikuAuahDark** [comment]
That explains everything. I think it's related to #258. Can you try the GitHub-compiled binaries from a81931be2cbe39181bc8d7db453eb4f1203e8c98? You need to uninstall existing app first.

**Comment by risejs** [comment]
I can't, only apk.

**Comment by MikuAuahDark** [comment]
Uh, yes? Install the `love-android-debug.apk` in https://github.com/love2d/love-android/actions/runs/7157034022

**Comment by risejs** [comment]
No, the same crash.

**Comment by risejs** [comment]
However, 11.5 work on Android 8 arm64-v8a (Tablet)...

**Comment by MikuAuahDark** [comment]
That crash seems to be very rare and weird. There's only 1 reported crash in SO: https://stackoverflow.com/q/57922110

**Comment by MikuAuahDark** [comment]
8a3d635cdb2a32feff5fb57f65b8469e48f74152 probably solve the issue. Can you try installing `love-android-debug.apk` in [https://github.com/love2d/love-android/actions/runs/7306340688](https://github.com/love2d/love-android/actions/runs/7306340688)? Again, you need to uninstall existing application first.

**Comment by risejs** [comment]
No, the same.

**Comment by MikuAuahDark** [comment]
I think I fixed it in d1f74df6866a3697146fec401683e880b6d9ce46. Try it in here https://github.com/love2d/love-android/actions/runs/7319055241, same instructions.

**Comment by risejs** [comment]
Oh, yeah! It's working. Thank you.

Should I now only use the debug version until the next release?

**Comment by MikuAuahDark** [comment]
I plan to release hotfix version soon.

**Comment by ydw222333** [comment]
main version have the same crash in Android10.
use "// setIntent(null);" can fix it;
why you still use "setIntent(null);" in main version?
Don't set the intent to null, only set the intent data to null.

**Comment by MikuAuahDark** [comment]
Do you get the exact same crash in Android 10 with exact stack trace? If not, then please create new issue.

The `main` branch now correspond to upcoming LOVE 12.0. The For LOVE 11.x releases, checkout `11.x` branch.
