### ISSUE TITLE
/love-android/wiki/Game-Packaging is outdated

### ISSUE THREAD

**Issue by roroire** [love2d/love-android#264]
https://github.com/love2d/love-android/wiki/Game-Packaging tells to rename a few files to rename your project and version, they being app/build.gradle and app/src/main/AndroidManifest.xml, but they point to variables elsewhere, under bundle.properties

**Comment by flamendless** [comment]
You use this as an additional reference https://github.com/flamendless/love-android-extensions

**Comment by MikuAuahDark** [comment]
Updated, thanks.
