### ISSUE TITLE
 SDK location not found. But SDK location is right

### ISSUE THREAD

**Issue by roroire** [love2d/love-android#266]
both ANDROID_HOME and ANDROID_SDK_ROOT are the same:  
```
      echo $ANDROID_HOME
~/Android
      echo $ANDROID_SDK_ROOT
~/Android
      ls ~/Android
cmdline-tools  licenses  ndk  platforms
```

JDK17 is installed:
```
sudo dnf install java-17-openjdk-devel.x86_64 java-17-openjdk.x86_64
```

and as you can see, the NDK is installed as well. However, on `./gradlew assembleEmbedNoRecord` I get:  
`SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable`

I know this isn't a miss of my OS nor love-android, because it worked a few weeks ago, however something must be wrong, and as I can not see it myself, am trying with this project, and seemingly did everything right, I think you guys may spot something I did not. I do not know where else to search, I tried slackoverflow, youtube, LLMs, but no luck.

I am not using Android Studio

**Comment by MikuAuahDark** [comment]
If `~/Android` has `home` and `sdk` folder, then the correct `$ANDROID_HOME` must be `~/Android/sdk`.

Not related to LOVE rather than system configuration. Closing as invalid.

**Comment by roroire** [comment]
could you at least point me where to ask such questions when all else fails? since I moved the sdk to `~/Android/sdk` and redefined the `$ANDROID_HOME` to it and I still get the error, @MikuAuahDark on this project

**Comment by MikuAuahDark** [comment]
If you search for "SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable" over the internet, you'll get lots of insights.

Generally, your `$ANDROID_HOME` should point to directory that has `platform-tools` and other folders in it. For example, this is correct directory that `$ANDROID_HOME` should point to, in Windows.
![gambar](https://github.com/love2d/love-android/assets/7500438/06dece97-ccd2-40eb-bcef-7c9ff4930b7b)

Also please note that this issue tracker is not meant for general system configuration troubleshooting. These can vary by OS.
