### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by parker-tyler** [love2d/love-android#270]
![Screenshot_20240403-141243.png](https://github.com/love2d/love-android/assets/163140586/d0ff6b77-f2a1-44e9-9f9b-08ef2454b0be)
On the Google Pixel 7 Pro, running stock android, there is a weird rendering bug where it seems that 2/3 of the screen is not rendering. All elements behind the black quarter circle are still interactive. Same game file runs with no graphical issues on a OnePlus device.

**Comment by slime73** [comment]
Am I right in assuming you're not the developer of Balatro? This bug report doesn't have enough information to be actionable, or even to know whether this is the right place for the report.

If you're trying to run someone's game on a platform it doesn't support and don't want to get your hands dirty with debugging, you'll probably need to wait for an official release of the game on that platform.

**Comment by MikuAuahDark** [comment]
If you're officially assigned to port Balatro to mobile, then without minimal reproducible example, we can't help.

If you're regular user loading Balatro exe to LOVE Loader (which works for some reason), then please read what Sasha said.
