### ISSUE TITLE
Play store APK targets old SDK and cannot install on new Android devices

### ISSUE THREAD

**Issue by idanmiara** [love2d/love-android#271]
Hi, 
Is this the official version of LÖVE for Android? 
https://play.google.com/store/apps/details?id=org.love2d.android
It targets old Android SDK and cannot be installed natively on newer devices. 

* This app isn't available for your device because it was made for an older version of Android. 
* This app is not available for any of your devices

I could get the apk using evozi and it does install on Android 14. I run aome basic basic love files and they do seem to work. 
https://storage.evozi.com/apk/dl/20/09/18/org.love2d.android_29.apk

**Comment by MikuAuahDark** [comment]
Currently the Play Store was paintained by the original LOVE Android developers. The latest APK can be found in the releases page of the main LOVE repository: https://github.com/love2d/love/releases/tag/11.5
