### ISSUE TITLE
`love.system.openURL` immediately crashes the application

### ISSUE THREAD

**Issue by VicKaoy** [love2d/love-android#273]
Using `love.system.openURL` function in any game will make the application crash with no error screen. (Currently I'm using Android 10 if that matters)

Can't send a logcat because I don't have a PC for it. :/

**Comment by VicKaoy** [comment]
Forgot to comment whoops! This is on the latest LÖVE workflow.

**Comment by MikuAuahDark** [comment]
Latest workflow as in `main` or `11.x`?

**Comment by VicKaoy** [comment]
Latest in `main`.

**Comment by MikuAuahDark** [comment]
Thanks for reporting. Please pull the latest `main` branch (including its submodules) to get the fix.
