### ISSUE TITLE
Savedata is inaccessable without SD card

### ISSUE THREAD

**Issue by polypoyo** [love2d/love-android#275]
/data/data requires root to access. Some games, such as [those with modloaders](https://kristal.cc) rely on the user being able to access savedata. This is impossible without root or an ADB shell.

Particularly impactful on GrapheneOS, where rooting defeats the point of the project.

Possibility related to #269, although this one is more severe.

**Comment by MikuAuahDark** [comment]
LOVE uses `/data/data` if you don't specify `t.externalstorage = true` in the `conf.lua`. Please ask the respective developers to have `t.externalstorage = true` in their `conf.lua`.

**Comment by MikuAuahDark** [comment]
No. That's tracked on #269.

Pada Sab, 6 Jul 2024, 23.47, polypoyo ***@***.***> menulis:
