### ISSUE TITLE
launching love with activity manager

### ISSUE THREAD

**Issue by andreyorst** [love2d/love-android#278]
Hello! This is more of a question, rather than an issue, but I don't see the discussion section in this project. Feel free to close this if it doesn't apply to the project's issue process.

LOVE 11.3 allowed to launch the app via the activity manager from Termux, like so:

    am start -d "file:///sdcard/game.love" --user 0 org.love2d.android/.GameActivity

This was convenient when developing a game on the phone.

After updating to 11.5 this no longer works, due to Android sandboxing (I presume). However, there's now an additional LOVE Launcher, so I wonder if it is possible to use it in a similar way. Manually opening the packaged `game.love` file works fine, it's just a bit tedious, and I'd like to be able to automate this process.

Additionally, I noticed that while the LOVE is running, repeated calls to `am` with the `-S` flag didn't restart the app. I'm not sure if that's because I have no permission to restart the app, or because the Android build doesn't support this. As a result, previously opened LOVE had to be closed before running `am` again. It's a small hindrance, but it adds up over time while iterating on the game.

**Comment by MikuAuahDark** [comment]
Android bans the usage of `file://` URI starting in Android 7, so unfortunately there will be no way of launching LOVE through activity manager anymore.

**Comment by radgeRayden** [comment]
The way I do it when developing with termux is to have a script that creates a love file, copies to accessible storage then uses xdg-open to launch the game with the launcher.

**Comment by andreyorst** [comment]
@MikuAuahDark I see. It still works for me on Android 14 though with LOVE 11.3 though, so I'm not sure what do you mean by the ban of `file://`. Do you have more info on this, I'd like to read about the internals a bit more.

@radgeRayden, thanks, good to know! Do you have an example? When I try `xdg-open ~/downloads/game.love` I get the "no game" screen no matter the version I try. Maybe I need some flags? The `--chooser` flag gives me the option of love, but not love loader.

**Comment by radgeRayden** [comment]
@andreyorst here's my actual script: 
```
#!/usr/bin/fish

set -l DIR (realpath (dirname (status --current-filename)))
echo $DIR
pushd $DIR
rm -rf ./dist
mkdir ./dist
cp -rf main.lua conf.lua settings.lua ./src ./lib ./assets ./dist
set -l NAME (string match -rg ".+/(.+\$)" $DIR)
set -l LOVEFILE "$NAME.love"
pushd ./dist
zip -ru  "$LOVEFILE" .
xdg-open ./$LOVEFILE
popd
popd
```

But now that you mention it, I think I open with love, not the loader.

**Comment by MikuAuahDark** [comment]
The `file://` bans is documented here https://developer.android.com/about/versions/nougat/android-7.0-changes#permfilesys

**Comment by andreyorst** [comment]
@MikuAuahDark thanks for the info! 

@radgeRayden thanks! It's weird that for me this approach gives the default "no game" screen. What version of LOVE do you use?

**Comment by radgeRayden** [comment]
> @MikuAuahDark thanks for the info! 
> 
> @radgeRayden thanks! It's weird that for me this approach gives the default "no game" screen. What version of LOVE do you use?

11.5.0

**Comment by andreyorst** [comment]
OK, thanks. If I'll figure this out, I'll post here what I found.

Was reading https://github.com/love2d/love-android/issues/194, and I gotta say, that doing game dev (or any kind of development) on the phone is not as weird or unnatural. Termux can get you pretty far, and modern phones are practically full-blown computers in terms of power. I did a lot of projects over the last 10 years from my phone, and lately, it's becoming harder to do "thanks" to Google, which is a shame.

**Comment by dkonsoul** [comment]
Hello! I found a solution that works for me, via Termux (you will need to have termux-api installed).

I am using the following script:

`# Check if path is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 /path/to/game"
  exit 1
fi

GAME_DIR="$1"
# Check if the directory exists
if [ ! -d "$GAME_DIR" ]; then
  echo "Directory not found: $GAME_DIR"
  exit 1
fi

# Navigate to the game directory
cd "$GAME_DIR" || exit

# Create the .love file
zip -r game.love *

# Share the .love file using termux-share
termux-share -d game.love`

termux-share creates a content:// URI, which is handled by the system's ContentProvider and bypasses the limitations of file:// URIs.

**Comment by dkonsoul** [comment]
Hello! I found a solution that works for me, via Termux (you will need to have termux-api installed).

I am using the following script:

`
# Check if path is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 /path/to/game"
  exit 1
fi

GAME_DIR="$1"
# Check if the directory exists
if [ ! -d "$GAME_DIR" ]; then
  echo "Directory not found: $GAME_DIR"
  exit 1
fi

# Navigate to the game directory
cd "$GAME_DIR" || exit

# Create the .love file
zip -r game.love *

# Share the .love file using termux-share
termux-share -d game.love
`

termux-share creates a content:// URI, which is handled by the system's ContentProvider and bypasses the limitations of file:// URIs.

**Comment by dkonsoul** [comment]
Hello! I found a solution that works for me, via Termux (you will need to have termux-api installed).

I am using the following script:

```
# Check if path is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 /path/to/game"
  exit 1
fi

GAME_DIR="$1"
# Check if the directory exists
if [ ! -d "$GAME_DIR" ]; then
  echo "Directory not found: $GAME_DIR"
  exit 1
fi

# Navigate to the game directory
cd "$GAME_DIR" || exit

# Create the .love file
zip -r game.love *

# Share the .love file using termux-share
termux-share -d game.love
```

termux-share creates a content:// URI, which is handled by the system's ContentProvider and bypasses the limitations of file:// URIs.
