### ISSUE TITLE
basic game crashes on input handeling

### ISSUE THREAD

**Issue by nevakrien** [love2d/love-android#283]
I am not sure whats the cause but a fairly simple game loop with 3 input shapes crashes when i drag my finger fast. 
basically on a drag even i would just update cordinates in some global varibles and then use those to render a circle. 
my phone is fairly capble rendering wise so its strange something this small causes a crash. 

i am runing a .love file with the loader instead of a packaged situation. i dont know i that matters...

**Comment by slime73** [comment]
Does it hard-crash, or show an error screen? Can you share your code?

**Comment by nevakrien** [comment]
hard crash 
i am using whats on the website **love-11.5-android.apk**
project is here https://github.com/nevakrien/lua_game

it also has bad frame rate before so this may be an oom killer situation. the app is very low on cpu usage i ran it on my PC it avraged 0.07 cpu utilization so its not like anything intresting is happening...

**Comment by slime73** [comment]
> this may be an oom killer situation

Yep – a new canvas is being created every frame and only deleted once the garbage collector runs, so you're going to have a large buildup of graphics memory pretty quickly.

Typically you should only create new objects during a loading step or when they're first used.

**Comment by slime73** [comment]
The GC is normally more forgiving, but it doesn't know the actual total memory size of love objects (especially graphics objects which use VRAM) so unfortunately it doesn't know to collect as frequently as it should in that situation.
