### ISSUE TITLE
Entire ZIP file is loaded into memory

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#64]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/63) by Seppi (Bitbucket: [josefnpat](https://bitbucket.org/josefnpat), GitHub: [josefnpat](https://github.com/josefnpat)).**

----------------------------------------

So I've found that when a game is launched, the entire zip is loaded into memory.

For a `game.love`:

    -rw-r--r-- 1 seppi users 159M May  9 16:42 game.love

It uses this much memory on launch:

    433969 kB: com.binarycocoa.hdf (pid 4155)

For a `game.love`:

    -rw-r--r-- 1 seppi users 196M May  9 16:36 game.love

It uses this much memory on launch:

    472216 kB: com.binarycocoa.hdf (pid 4766)

Shouldn't `love-android-sdl2` be loading in the content of the zip from the source, not from a zip loaded into memory? Perhaps if this is hard to work around, the system could use the `assets/` folder as a directory (e.g. `assets/main.lua`) instead of `assets/game.love`.

**Comment by MikuAuahDark** [comment]
Closing as this is no longer the case.
