### ISSUE TITLE
Communication with "Host" - android application

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#70]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/69) by Karthik T (Bitbucket: [ktaragorn](https://bitbucket.org/ktaragorn), GitHub: [ktaragorn](https://github.com/ktaragorn)).**

----------------------------------------

We are integrating your port with our application in order to create small games that we can download and run OTA.. However we have need to send messages to and from the Java Layer.. Is this on the timeline? I mean something like http://docs.coronalabs.com/daily/coronacards/android/communication.html . I was going to see if I could make a 2 way channel which could carry a table/hashmap.. but am lost as to where to start.

**Comment by MikuAuahDark** [comment]
I think https://bitbucket.org/bartbes/jniwrap works when communicating to Java side from Lua. However, to communicate from Java side to Lua, I think it's possible to expose `love.event.push` function in Java side.
