### ISSUE TITLE
support for google play games services

### ISSUE THREAD

**Issue by slime73** [love2d/love-android#78]
**[Original report](https://bitbucket.org/MartinFelis/love-android-sdl2/issue/77) by Anonymous.**

----------------------------------------

Not sure if this is already possible. But it would be great, when we can use it for multiplayer support, achievement support and more.

**Comment by MikuAuahDark** [comment]
See my first comment in #70. This should be easy to implement once what I said there has been implemented.

**Comment by MikuAuahDark** [comment]
I don't think we'll add Google API as our build-time dependency. Furthermore there's no suitable API for it (see https://github.com/love2d/love-android/issues/70#issuecomment-1134053950 for more information).
